#!/bin/bash
# bootstrap/generators/boundaries.sh — Auto-generate .context/boundaries.yml
#
# Usage: generate_boundaries <target_dir> <domain> <name>

generate_boundaries() {
  local target_dir="$1" domain="$2" name="$3"

  mkdir -p "${target_dir}/.context"

  if [ -f "${target_dir}/.context/boundaries.yml" ]; then
    echo "  → .context/boundaries.yml already exists, skipping."
    return
  fi

  local generated_paths=""

  # Auto-detect generated paths from .gitignore
  if [ -f "${target_dir}/.gitignore" ]; then
    while IFS= read -r line; do
      line=$(echo "$line" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
      [[ -z "$line" || "$line" == \#* || "$line" == "!"* ]] && continue
      generated_paths="${generated_paths}    - ${target_dir}/${line}\n"
    done < "${target_dir}/.gitignore"
  fi

  # Always-include generated paths
  local always_generated=("node_modules" "dist" "build" ".next" "coverage" "docs/.runtime")
  for p in "${always_generated[@]}"; do
    if ! echo "$generated_paths" | grep -qF "  - ${target_dir}/${p}"; then
      generated_paths="${generated_paths}    - ${target_dir}/${p}\n"
    fi
  done

  cat > "${target_dir}/.context/boundaries.yml" << HEREDOC
---
# Boundaries — where this agent is allowed to write
# Generated by naprolom bootstrap

pristine:
  - ${target_dir}/
  - ${target_dir}/src/
  - ${target_dir}/tests/
  - ${target_dir}/docs/
  - ${target_dir}/.context/

generated:
  # Auto-detected from .gitignore
$(echo -e "$generated_paths")
  - ${target_dir}/docs/.runtime/
  - ${target_dir}/.claude/

secrets:
  - ${target_dir}/.env
  - ${target_dir}/.env.*
  - ${target_dir}/*.key
  - ${target_dir}/*.pem
  - ${target_dir}/secrets/
HEREDOC

  echo "  → .context/boundaries.yml created."
}
