#!/bin/bash
# bootstrap/generators/claude-md.sh — Generate CLAUDE.md snippet
#
# API: generate TARGET REGISTRY

generate() {
  local target_dir="$1" registry="$2"

  if [ -f "${target_dir}/CLAUDE.md" ]; then
    echo "  → CLAUDE.md already exists, skipping."
    return
  fi

  cat > "${target_dir}/CLAUDE.md" << HEREDOC
# CLAUDE.md — AI Agent Quickstart

## Project Identity

- Name: $(basename "$target_dir")
- Domain: unknown
- Stack: unknown
- Runtime: naprolom v1.7

## Documentation Layout

\`\`\`
docs/
  architecture/     # topology, domain model, invariants
  adr/              # Architecture Decision Records
  specs/            # specifications (draft → review → approved → implemented)
  audits/           # audit reports, reality checks
  backlog/          # backlog, TODO, wishlist
  api/              # API documentation
  .runtime/         # generated by bootstrap (do not edit directly)
    runtime/        # naprolom runtime
    documentation/  # templates, validation, schemas
    agents/         # agent roles
    knowledge/      # knowledge base
    sops/           # standard operating procedures
    bootstrap/      # bootstrap scripts
    engine/         # reality engine
\`\`\`

## Before Writing Documentation

1. Read \`.context/boundaries.yml\` — know what you can touch
2. Read \`docs/.runtime/playbook/playbook-v2.md\` — understand the protocol
3. Check \`docs/.runtime/registry.yaml\` for available components

## Key Files

- \`.context/project.yml\` — project metadata
- \`.context/boundaries.yml\` — boundary rules
- \`.context/agent-entry.md\` — agent entry protocol
- \`docs/.runtime/state-machine.yaml\` — valid states and transitions
HEREDOC
  echo "  → CLAUDE.md snippet created."
}
